{% set name = "pydaqmx" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyDAQmx-{{ version }}.tar.gz
  sha256: c236a1abc8aeba24ebf20a662b2dcb16c797cc1dbe37e120d6352f74804da8f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pythonhosted.org/PyDAQmx/
  summary: Interface to the National Instruments PyDAQmx driver
  doc_url: https://pythonhosted.org/PyDAQmx/
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - untzag
    - ksunden
